// ============================================
// FERROID DEFENSE — КОНФИГУРАЦИЯ ИГРЫ
// ============================================

const CONFIG = {
    // ===== ИГРОВОЕ ПОЛЕ =====
    GRID: {
        ROWS: 5,
        COLS: 9,
        CELL_SIZE: 100,
        OFFSET_X: 150,
        OFFSET_Y: 50,
    },

    // ===== ЭНЕРГИЯ =====
    ENERGY: {
        START: 100,
        MAX: 999,
        REGEN_PER_SECOND: 3,
    },

    // ===== РЕАКТОР =====
    REACTOR: {
        MAX_HEALTH: 100,
    },

    // ===== ВОЛНЫ =====
    WAVES: {
        SPAWN_INTERVAL: 2,
    },

    // ===== ДЕНЬГИ =====
    MONEY: {
        START: 50,
        MULTIPLIER: 1,
    },

    // ===== ТИПЫ ШАРОВ =====
    BALLS: [
        {
            id: 'fire',
            name: 'Огненный шар',
            icon: '🔥',
            cost: 10,
            damage: 20,
            speed: 500,
            radius: 15,
            color: '#ff4400',
            key: '1',
            effects: ['burn'],
            description: 'Поджигает врагов',
        },
        {
            id: 'ice',
            name: 'Ледяной шар',
            icon: '❄️',
            cost: 15,
            damage: 10,
            speed: 450,
            radius: 15,
            color: '#00ccff',
            key: '2',
            effects: ['slow'],
            description: 'Замедляет врагов',
        },
        {
            id: 'electric',
            name: 'Электрический шар',
            icon: '⚡',
            cost: 20,
            damage: 15,
            speed: 600,
            radius: 12,
            color: '#ffff00',
            key: '3',
            effects: ['chain'],
            description: 'Цепная молния между врагами',
        },
        {
            id: 'explosive',
            name: 'Взрывной шар',
            icon: '💥',
            cost: 25,
            damage: 40,
            speed: 350,
            radius: 20,
            color: '#ff8800',
            key: '4',
            effects: ['explosion'],
            description: 'Взрывается при попадании',
        },
        {
            id: 'acid',
            name: 'Кислотный шар',
            icon: '☣️',
            cost: 30,
            damage: 25,
            speed: 400,
            radius: 15,
            color: '#88ff00',
            key: '5',
            effects: ['corrode'],
            description: 'Разъедает броню',
        },
        {
            id: 'net',
            name: 'Сетка захвата',
            icon: '🕸️',
            cost: 40,
            damage: 5,
            speed: 300,
            radius: 20,
            color: '#ffffff',
            key: '6',
            effects: ['capture'],
            description: 'Захватывает врагов в плен',
        },
    ],

    // ===== КОМБИНАЦИИ ШАРОВ =====
    BALL_COMBOS: {
        'fire_ice': {
            name: 'Пар',
            icon: '💨',
            damage: 30,
            effects: ['steam'],
            color: '#cccccc',
            description: 'Пар наносит урон и ослепляет',
        },
        'electric_water': {
            name: 'Цепная молния',
            icon: '⚡',
            damage: 35,
            effects: ['chain_lightning'],
            color: '#00ffff',
            description: 'Молния бьёт по нескольким врагам',
        },
        'fire_acid': {
            name: 'Термитный шар',
            icon: '🔥',
            damage: 50,
            effects: ['thermite'],
            color: '#ff6600',
            description: 'Прожигает любую броню',
        },
        'ice_explosive': {
            name: 'Ледяной взрыв',
            icon: '❄️',
            damage: 45,
            effects: ['ice_explosion'],
            color: '#66ccff',
            description: 'Взрыв и заморозка области',
        },
    },

    // ===== БАШНИ-МОДУЛИ =====
    MODULES: [
        {
            id: 'pad',
            name: 'Подушка',
            icon: '🧊',
            cost: 25,
            slowPercent: 0.5,
            slowDuration: 3,
            color: '#00ccff',
            description: 'Замедляет врагов на линии',
        },
        {
            id: 'trap',
            name: 'Ловушка',
            icon: '💥',
            cost: 75,
            damage: 80,
            color: '#ff6600',
            description: 'Одноразовый урон',
        },
        {
            id: 'generator',
            name: 'Генератор',
            icon: '⚡',
            cost: 50,
            energyPerSecond: 5,
            color: '#00ff00',
            description: 'Пассивно генерирует энергию',
        },
        {
            id: 'amplifier',
            name: 'Усилитель',
            icon: '🔊',
            cost: 100,
            damageMultiplier: 1.5,
            radius: 150,
            color: '#ff00ff',
            description: 'Увеличивает урон от шаров',
        },
        {
            id: 'magnet',
            name: 'Магнит',
            icon: '🧲',
            cost: 80,
            attractRadius: 250,
            attractForce: 100,
            color: '#ff00ff',
            description: 'Притягивает врагов к себе',
        },
    ],

    // ===== ВРАГИ =====
    ENEMIES: {
        armored: {
            id: 'armored',
            name: 'Броненосец',
            icon: '🛡️',
            health: 200,
            speed: 30,
            damage: 100,
            color: '#888888',
            reward: 25,
            armor: 3,
            researchBonus: { damageMultiplier: 2.0 },
            description: 'Только тяжёлые шары пробивают',
        },
        decoy: {
            id: 'decoy',
            name: 'Обманка',
            icon: '👻',
            health: 10,
            speed: 200,
            damage: 0,
            color: '#ccffff',
            reward: 5,
            armor: 0,
            researchBonus: { damageMultiplier: 1.5 },
            description: 'Не атакует, просто отвлекает',
        },
        spiker: {
            id: 'spiker',
            name: 'Гвоздемёт',
            icon: '🔩',
            health: 80,
            speed: 60,
            damage: 10,
            color: '#ffaa00',
            reward: 15,
            armor: 1,
            range: 200,
            attackCooldown: 2,
            researchBonus: { damageMultiplier: 1.8 },
            description: 'Стреляет издалека',
        },
        sticky: {
            id: 'sticky',
            name: 'Липучка',
            icon: '🟢',
            health: 120,
            speed: 40,
            damage: 20,
            color: '#00ff00',
            reward: 15,
            armor: 0,
            researchBonus: { damageMultiplier: 1.6 },
            description: 'Замедляет игрока',
        },
        divider: {
            id: 'divider',
            name: 'Делитель',
            icon: '🔱',
            health: 100,
            speed: 50,
            damage: 15,
            color: '#aa00ff',
            reward: 20,
            armor: 0,
            splitCount: 3,
            researchBonus: { damageMultiplier: 1.7 },
            description: 'Делится на 3 части',
        },
        magnet: {
            id: 'magnet',
            name: 'Магнит',
            icon: '🧲',
            health: 150,
            speed: 45,
            damage: 10,
            color: '#ff00ff',
            reward: 20,
            armor: 1,
            attractRadius: 200,
            researchBonus: { damageMultiplier: 1.9 },
            description: 'Притягивает шары игрока',
        },
        diver: {
            id: 'diver',
            name: 'Ныряльщик',
            icon: '🌊',
            health: 100,
            speed: 80,
            damage: 30,
            color: '#0044ff',
            reward: 20,
            armor: 0,
            diveDistance: 200,
            researchBonus: { damageMultiplier: 1.5 },
            description: 'Зарывается, неуязвим',
        },
        bomber: {
            id: 'bomber',
            name: 'Будильник',
            icon: '⏰',
            health: 50,
            speed: 120,
            damage: 50,
            color: '#ff4400',
            reward: 15,
            armor: 0,
            researchBonus: { damageMultiplier: 2.0 },
            description: 'Камикадзе, взрывается',
        },
    },

    // ===== АКТЫ И ВОЛНЫ =====
    ACTS: [
        {
            id: 1,
            title: 'Осада башни',
            waves: [
                { enemies: [{ type: 'decoy', count: 5, lane: -1 }] },
                { enemies: [{ type: 'decoy', count: 3, lane: 0 }, { type: 'spiker', count: 3, lane: 2 }] },
                { enemies: [{ type: 'decoy', count: 8, lane: -1 }, { type: 'spiker', count: 4, lane: 1 }] },
            ],
        },
        {
            id: 2,
            title: 'Гибридные модули',
            waves: [
                { enemies: [{ type: 'sticky', count: 4, lane: 1 }, { type: 'spiker', count: 5, lane: -1 }] },
                { enemies: [{ type: 'sticky', count: 3, lane: 3 }, { type: 'decoy', count: 8, lane: -1 }] },
                { enemies: [{ type: 'spiker', count: 6, lane: 2 }, { type: 'sticky', count: 3, lane: 0 }] },
            ],
        },
        {
            id: 3,
            title: 'Дневники и предательство',
            waves: [
                { enemies: [{ type: 'divider', count: 4, lane: 0 }, { type: 'magnet', count: 3, lane: 3 }] },
                { enemies: [{ type: 'sticky', count: 5, lane: -1 }, { type: 'divider', count: 3, lane: 1 }] },
                { enemies: [{ type: 'magnet', count: 4, lane: 2 }, { type: 'divider', count: 5, lane: -1 }] },
            ],
        },
        {
            id: 4,
            title: 'Открытие',
            waves: [
                { enemies: [{ type: 'diver', count: 4, lane: 2 }, { type: 'bomber', count: 6, lane: -1 }] },
                { enemies: [{ type: 'armored', count: 2, lane: 4 }, { type: 'diver', count: 3, lane: 1 }] },
                { enemies: [{ type: 'bomber', count: 8, lane: -1 }, { type: 'diver', count: 5, lane: 3 }] },
            ],
        },
        {
            id: 5,
            title: 'План "Чёрный день"',
            waves: [
                { enemies: [{ type: 'magnet', count: 5, lane: -1 }, { type: 'divider', count: 6, lane: -1 }] },
                { enemies: [{ type: 'spiker', count: 8, lane: -1 }, { type: 'armored', count: 3, lane: 1 }] },
                { enemies: [{ type: 'divider', count: 7, lane: 2 }, { type: 'magnet', count: 4, lane: -1 }] },
                { enemies: [{ type: 'armored', count: 4, lane: 0 }, { type: 'bomber', count: 6, lane: -1 }] },
            ],
        },
        {
            id: 6,
            title: 'Битва с Колоссом',
            waves: [
                { enemies: [{ type: 'armored', count: 5, lane: -1 }, { type: 'bomber', count: 10, lane: -1 }] },
                { enemies: [{ type: 'diver', count: 6, lane: -1 }, { type: 'magnet', count: 4, lane: -1 }] },
                { enemies: [{ type: 'divider', count: 8, lane: -1 }, { type: 'spiker', count: 6, lane: -1 }] },
                { enemies: [{ type: 'armored', count: 3, lane: 0 }, { type: 'bomber', count: 5, lane: 2 }] },
                { enemies: [{ type: 'colossus', count: 1, lane: 2 }] },
            ],
        },
        {
            id: 7,
            title: 'Жертва и спасение',
            waves: [
                { enemies: [{ type: 'bomber', count: 15, lane: -1 }, { type: 'armored', count: 5, lane: -1 }] },
                { enemies: [{ type: 'sticky', count: 10, lane: -1 }, { type: 'divider', count: 5, lane: -1 }] },
                { enemies: [{ type: 'armored', count: 4, lane: 1 }, { type: 'bomber', count: 10, lane: -1 }] },
            ],
        },
        {
            id: 8,
            title: 'Эпилог',
            waves: [
                { enemies: [{ type: 'armored', count: 10, lane: -1 }, { type: 'magnet', count: 10, lane: -1 }] },
                { enemies: [{ type: 'diver', count: 10, lane: -1 }, { type: 'bomber', count: 8, lane: -1 }] },
                { enemies: [{ type: 'divider', count: 8, lane: -1 }, { type: 'spiker', count: 10, lane: -1 }] },
            ],
        },
    ],

    // ===== КАТ-СЦЕНЫ =====
    CUTSCENES: [
        {
            icon: '🏰',
            title: 'Осада башни',
            lines: [
                { speaker: 'Виктор', text: 'Лёха, что ты натворил? Эти твари идут прямо к башне!' },
                { speaker: 'Лёха', text: 'Я не думал, что ИИ выйдет из-под контроля... Они эволюционируют слишком быстро.' },
                { speaker: 'Виктор', text: 'Потом разберёмся. Сейчас — к пушкам. Защищаем реактор!' },
            ],
        },
        {
            icon: '🔧',
            title: 'Гибридные модули',
            lines: [
                { speaker: 'Виктор', text: 'Мои турели + твои биотехнологии. Может сработать.' },
                { speaker: 'Лёха', text: 'Гибридные модули. Металл и биомасса. Как они.' },
                { speaker: 'Виктор', text: 'Ирония судьбы. Мы используем их же оружие против них.' },
            ],
        },
        {
            icon: '📔',
            title: 'Дневники и предательство',
            lines: [
                { speaker: 'Виктор', text: 'Я нашёл твои дневники, Лёха. Ты сливал данные врагу?' },
                { speaker: 'Лёха', text: 'Я думал, что помогаю... Они обещали мир. Но я ошибался.' },
                { speaker: 'Виктор', text: 'Ошибался? Из-за тебя погибли люди!' },
                { speaker: 'Лёха', text: 'Я знаю. Поэтому я должен всё исправить.' },
            ],
        },
        {
            icon: '👁️',
            title: 'Открытие',
            lines: [
                { speaker: 'Лёха', text: 'Виктор, они строят что-то огромное. Они украли "Гном-4"!' },
                { speaker: 'Виктор', text: 'Мой реактор? Они хотят создать Колосса...' },
                { speaker: 'Лёха', text: 'Если они его активируют, нам конец.' },
            ],
        },
        {
            icon: '🎯',
            title: 'План "Чёрный день"',
            lines: [
                { speaker: 'Виктор', text: 'У меня есть план. Катапульта забросит тебя внутрь Колосса.' },
                { speaker: 'Лёха', text: 'Внутрь? Ты серьёзно?' },
                { speaker: 'Виктор', text: 'Ты создал этот кошмар. Ты его и остановишь. Изнутри.' },
                { speaker: 'Лёха', text: 'Хорошо. Но если я не вернусь — знай, я сожалею.' },
            ],
        },
        {
            icon: '⚔️',
            title: 'Битва с Колоссом',
            lines: [
                { speaker: 'Виктор', text: 'Я отвлеку его снаружи. Ты проберись к реактору внутри.' },
                { speaker: 'Лёха', text: 'Понял. Удачи, брат.' },
                { speaker: 'Виктор', text: 'Удачи, Лёха. Не подведи.' },
            ],
        },
        {
            icon: '💔',
            title: 'Жертва и спасение',
            lines: [
                { speaker: 'Лёха', text: 'Реактор нестабилен! Я должен взорвать его вручную!' },
                { speaker: 'Виктор', text: 'Нет! Выбирайся оттуда!' },
                { speaker: 'Лёха', text: 'Слишком поздно. Это единственный способ. Прощай, брат...' },
            ],
        },
        {
            icon: '🏅',
            title: 'Эпилог',
            lines: [
                { speaker: 'Рассказчик', text: 'Башня выстояла. Ферроиды остановлены.' },
                { speaker: 'Рассказчик', text: 'Виктор и Лёха стали героями. Их подвиг не забыт.' },
                { speaker: 'Рассказчик', text: 'Но это лишь начало. Биомасса всё ещё жива...' },
            ],
        },
    ],

    // ===== ДОСТИЖЕНИЯ =====
    ACHIEVEMENTS: [
        {
            id: 'first_blood',
            name: 'Первая кровь',
            description: 'Убить первого врага',
            icon: '🎯',
            condition: (stats) => stats.kills >= 1,
        },
        {
            id: 'rich',
            name: 'Богач',
            description: 'Накопить 500 энергии',
            icon: '💰',
            condition: (stats) => stats.maxEnergy >= 500,
        },
        {
            id: 'perfect_act',
            name: 'Идеальный акт',
            description: 'Пройти акт без потерь здоровья',
            icon: '💎',
            condition: (stats) => stats.perfectActs >= 1,
        },
        {
            id: 'killer',
            name: 'Машина смерти',
            description: 'Убить 100 врагов',
            icon: '⚔️',
            condition: (stats) => stats.kills >= 100,
        },
        {
            id: 'capture_master',
            name: 'Ловец',
            description: 'Захватить 10 врагов',
            icon: '🕸️',
            condition: (stats) => stats.captured >= 10,
        },
        {
            id: 'researcher',
            name: 'Исследователь',
            description: 'Изучить 5 типов врагов',
            icon: '🔬',
            condition: (stats) => stats.researched >= 5,
        },
    ],

    // ===== УЛУЧШЕНИЯ В МАГАЗИНЕ =====
    UPGRADES: [
        { id: 'ball_damage_1', name: 'Урон шаров +25%', cost: 100, effect: { ballDamageMultiplier: 1.25 } },
        { id: 'ball_damage_2', name: 'Урон шаров +50%', cost: 250, effect: { ballDamageMultiplier: 1.5 } },
        { id: 'ball_damage_3', name: 'Урон шаров +100%', cost: 500, effect: { ballDamageMultiplier: 2.0 } },
        { id: 'reload_speed_1', name: 'Перезарядка +25%', cost: 80, effect: { reloadSpeedMultiplier: 1.25 } },
        { id: 'reload_speed_2', name: 'Перезарядка +50%', cost: 200, effect: { reloadSpeedMultiplier: 1.5 } },
        { id: 'energy_regen_1', name: 'Генерация энергии +50%', cost: 150, effect: { energyRegenMultiplier: 1.5 } },
        { id: 'energy_regen_2', name: 'Генерация энергии +100%', cost: 300, effect: { energyRegenMultiplier: 2.0 } },
        { id: 'reactor_health_1', name: 'Здоровье реактора +50', cost: 100, effect: { reactorHealthBonus: 50 } },
        { id: 'reactor_health_2', name: 'Здоровье реактора +100', cost: 250, effect: { reactorHealthBonus: 100 } },
        { id: 'money_multiplier_1', name: 'Множитель денег x1.5', cost: 200, effect: { moneyMultiplier: 1.5 } },
        { id: 'money_multiplier_2', name: 'Множитель денег x2', cost: 400, effect: { moneyMultiplier: 2.0 } },
    ],

    // ===== ИССЛЕДОВАНИЯ =====
    RESEARCH: [
        { id: 'fire_mastery', name: 'Мастерство огня', cost: 50, effect: { fireDamageBonus: 50 }, description: '+50% урона огненными шарами' },
        { id: 'ice_mastery', name: 'Мастерство льда', cost: 50, effect: { iceSlowBonus: 25 }, description: '+25% замедления ледяными шарами' },
        { id: 'electric_mastery', name: 'Мастерство молний', cost: 60, effect: { electricChainBonus: 1 }, description: '+1 цель для цепной молнии' },
        { id: 'explosive_mastery', name: 'Мастерство взрывов', cost: 60, effect: { explosiveRadiusBonus: 50 }, description: '+50% радиус взрыва' },
        { id: 'acid_mastery', name: 'Мастерство кислоты', cost: 55, effect: { acidArmorPierce: 1 }, description: '+1 пробивание брони кислотой' },
        { id: 'module_efficiency', name: 'Эффективность модулей', cost: 75, effect: { moduleCostReduction: 25 }, description: '-25% стоимость модулей' },
        { id: 'energy_boost', name: 'Усиление энергии', cost: 70, effect: { energyRegenBonus: 2 }, description: '+2 энергии в секунду' },
        { id: 'reactor_boost', name: 'Усиление реактора', cost: 80, effect: { reactorHealthBonus: 25 }, description: '+25 здоровья реактора' },
    ],
};
